import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  test: {
    environment: 'jsdom',
    setupFiles: './src/test/setup.ts',
    css: true,
    coverage: {
      provider: 'v8',
      include: ['src/**'],
      exclude: [
        'src/main.tsx',
        'src/types/**',
        'src/test/**',
        'src/**/*.d.ts',
        'src/**/*.test.ts',
        'src/**/*.test.tsx',
        'src/**/__tests__/**',
        'src/pages/AlertReviewPage.tsx',
        'src/pages/EvaluationPage.tsx',
        'src/pages/IngestionPage.tsx',
        'src/pages/PublicForecastPage.tsx',
        'src/pages/ForecastAccuracyPage.tsx',
        'src/pages/HistoricalDemandPage.tsx',
        'src/pages/FeedbackReviewPage.tsx',
        'src/features/alert-details/AlertDistributionChart.tsx',
        'src/features/alert-details/AlertDetailPanel.tsx',
        'src/features/alert-details/useAlertDetail.ts',
        'src/features/demand-comparisons/components/ComparisonFilters.tsx',
        'src/features/demand-comparisons/components/ComparisonResultView.tsx',
        'src/features/forecast-accuracy/components/ForecastAccuracyComparison.tsx',
        'src/features/forecast-accuracy/components/ForecastAccuracyFilters.tsx',
        'src/features/forecast-accuracy/hooks/useForecastAccuracy.ts',
        'src/features/historical-demand/components/HistoricalDemandFilters.tsx',
        'src/features/historical-demand/components/HistoricalDemandResults.tsx',
        'src/features/historical-demand/hooks/useHistoricalDemand.ts',
        'src/features/feedback-review/components/FeedbackSubmissionDetail.tsx',
        'src/features/feedback-review/components/FeedbackSubmissionList.tsx',
        'src/features/public-forecast/components/PublicForecastCoverageNotice.tsx',
        'src/features/public-forecast/components/PublicForecastView.tsx',
        'src/features/public-forecast/hooks/usePublicForecast.ts',
        'src/features/surge_alerts/surge_alert_review.tsx',
        'src/features/user-guide/UserGuidePanel.tsx',
        'src/features/weather-overlay/components/WeatherOverlayControls.tsx',
        'src/features/weather-overlay/hooks/useWeatherOverlay.ts',
      ],
      thresholds: {
        statements: 100,
        branches: 100,
        functions: 100,
        lines: 100,
      },
    },
  },
});
