from app.core.auth import get_current_claims, require_operational_manager, require_planner_or_manager

require_forecast_trigger = require_operational_manager
require_forecast_reader = require_planner_or_manager
require_evaluation_trigger = require_operational_manager
require_evaluation_reader = require_planner_or_manager
require_forecast_alert_trigger = require_operational_manager
require_forecast_alert_reader = require_planner_or_manager
require_surge_alert_reader = require_planner_or_manager

require_visualization_reader = require_planner_or_manager
require_visualization_writer = require_operational_manager
require_historical_demand_reader = require_planner_or_manager
require_demand_comparison_reader = require_planner_or_manager
require_feedback_review_reader = require_planner_or_manager
require_forecast_accuracy_reader = require_planner_or_manager
require_authenticated_user = get_current_claims
